def monad1(number):
  w = int(l.pop(0))
xxxzxxxyyyyzyyyyz  w = int(l.pop(0))
xxxzxxxyyyyzyyyyz  w = int(l.pop(0))
xxxzxxxyyyyzyyyyz  w = int(l.pop(0))
xxxzxxxyyyyzyyyyz  w = int(l.pop(0))
xxxzxxxyyyyzyyyyz  w = int(l.pop(0))
xxxzxxxyyyyzyyyyz  w = int(l.pop(0))
xxxzxxxyyyyzyyyyz  w = int(l.pop(0))
xxxzxxxyyyyzyyyyz  w = int(l.pop(0))
xxxzxxxyyyyzyyyyz  w = int(l.pop(0))
xxxzxxxyyyyzyyyyz  w = int(l.pop(0))
xxxzxxxyyyyzyyyyz  w = int(l.pop(0))
xxxzxxxyyyyzyyyyz  w = int(l.pop(0))
xxxzxxxyyyyzyyyyz  w = int(l.pop(0))
xxxzxxxyyyyzyyyyz  print ("the answer is " + str(z))

monad1(input('gimme number: '))